name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type checking
      run: npx tsc --noEmit

    - name: Check Svelte files
      run: npx svelte-check --tsconfig ./tsconfig.json

    - name: Validate Tailwind config
      run: npx tailwindcss --help > /dev/null

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Run npm audit
      run: npm audit --audit-level=moderate || true

    - name: Check for outdated packages
      run: npm outdated || true

  test-builds:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Verify build outputs
      shell: bash
      run: |
        if [ ! -f "public/build/bundle.js" ]; then
          echo "Error: bundle.js not found!"
          exit 1
        fi
        if [ ! -f "public/build/bundle.css" ]; then
          echo "Error: bundle.css not found!"
          exit 1
        fi
        echo "✅ Build verification passed"