name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get version from tag
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ github.ref_name }}" \
          --title "Historian ${{ steps.get_version.outputs.version }}" \
          --notes "## Historian ${{ steps.get_version.outputs.version }}
        
        ### Installation
        1. Clone the repository
        2. Run \`npm install\`
        3. Run \`npm run build\`
        4. Run \`npm run electron\`
        
        ### Building Distributables
        - **macOS**: \`npm run dist-mac\`
        - **Windows**: \`npm run dist-win\`
        - **Linux**: \`npm run dist-linux\`
        
        ### What's New
        See [commit history](https://github.com/${{ github.repository }}/commits/${{ steps.get_version.outputs.version }}) for changes." \
          --draft=false \
          --prerelease=false